logo: IMG_4927.jpg
title: [Finnian J Wort]
description: [Articles and links]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
